[package]
name = "surrealdb-backup"
version = "0.1.4"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
rocksdb = { version = "0.23.0", features = ["lz4", "snappy"] }
